apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lg4wtiruo-nodejs
  janus-idp.io/tekton: lg4wtiruo-nodejs
  backstage.io/kubernetes-id: lg4wtiruo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lg4wtiruo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
